version: "3"
services:
  nwn2server:
    build:
      context: .
      dockerfile: ./docker/nwn2server/Dockerfile
    volumes:
      #- "${NWN2_INSTALL_DIR}:/opt/neverwinter_nights_2"
      - "wine:/root/wine"
    ports:
      - "${SERVER_PORT:-5121}:5121"

volumes:
  wine:
