version: "3"
services:
  nwn2server:
    container_name: nwn2server
    build:
      context: .
      dockerfile: ./docker/nwn2server/Dockerfile
    volumes:
      - "${NWN2_INSTALL_DIR}:/opt/nwn2"
      - "${NWN2_NWN2PLAYER_INI_PATH:-./docker/nwn2server/nwn2player.ini}:/opt/nwn2_stage/nwn2player.ini:ro"
      - "${NWN2_NWNX_INI_PATH:-./docker/nwn2server/nwnx.ini}:/opt/nwnx4/nwnx.ini:ro"
      - "nwn2_stage:/opt/nwn2_stage"
    ports:
      - "${SERVER_PORT:-5121}:5121/udp"

volumes:
  nwn2_stage: