version: "3"
services:
  nwn2server:
    container_name: nwn2server
    image: nwn2server:latest
    build:
      context: ..
      dockerfile: ./docker/nwn2server/Dockerfile
    volumes:
      - "${NWN2_INSTALL_DIR}:/opt/nwn2:ro"
      - "${NWN2_INSTALL_DIR}/Campaigns:/opt/nwn2_stage/Campaigns:ro"
      - "${NWN2_INSTALL_DIR}/Modules:/opt/nwn2_stage/Modules:ro"
      - "${NWN2_HOME_DIR}:/root/Neverwinter Nights 2"
    ports:
      - "${SERVER_PORT:-5121}:5121/udp"
    env_file: ./nwn2server/.env
