version: "3"
services:
  nwnx4:
    container_name: nwnx4
    image: nwnx4:latest
    build:
      context: ..
      dockerfile: ./docker/nwnx4/Dockerfile
    volumes:
      - "${NWNX4_USER_DIR}:/opt/nwnx4"
      - "${NWN2_INSTALL_DIR}:/srv/nwn2"
      - "${NWN2_HOME_DIR}:/root/Neverwinter Nights 2"
    ports:
      - "${SERVER_PORT:-5121}:5121/udp"
